// src/components/modal/ModalAddAddress.vue
<script setup lang="ts">
import { ref } from 'vue';
import FormAddAddress from '@/components/form/FormAddAddress.vue';

const modal = ref(null)

// Funções para abrir e fechar o modal
const openModal = () => modal.value?.showModal()
const closeModal = () => modal.value?.close()
</script>

<template>
  <div>
      <!-- Open the modal using document.getElementById('ID').showModal() method -->
      <button
        type='button'
        class='btn btn-primary btn-md w-full'
        @click="openModal()"
      >
        Adicionar novo endereço
      </button>
      <dialog id='modalAddAddress' class='modal' ref="modal">
        <div class='modal-box max-h-[80vh] overflow-y-auto'>
          <h3 class='font-bold text-lg text-center'>
            Adicione seu endereço
          </h3>
          <FormAddAddress closeModal="closeModal" />
        </div>
      </dialog>
  </div>
</template>

// next/src/components/modal/modal-add-address.tsx
'use client'
import React, { useRef } from 'react'
import FormAddAddress from 'src/components/form/form-add-address'

export default function ModalAddAddress() {
  const modalRef = useRef<HTMLDialogElement>(null)

  // Funções para abrir e fechar o modal
  const openModal = () => modalRef.current?.showModal()
  const closeModal = () => modalRef.current?.close()

  return (
    <>
      {/* Open the modal using document.getElementById('ID').showModal() method */}
      <button
        type='button'
        className='btn btn-primary btn-md w-full'
        onClick={() => openModal()}
      >
        Adicionar novo endereço
      </button>
      <dialog id='my_modal_1' className='modal' ref={modalRef}>
        <div className='modal-box max-h-[80vh] overflow-y-auto'>
          <h3 className='font-bold text-lg text-center'>
            Adicione seu endereço
          </h3>
          <FormAddAddress closeModal={closeModal} />
        </div>
      </dialog>
    </>
  )
}
