// src/components/form/FormAddAddress.vue
<script setup lang="ts">
import type { Address } from '@/services/flyfood-api/types'
import { useForm } from '@tanstack/vue-form'
import { useViaCEP } from '@/hooks/useViaCEP'
import { z } from 'zod/v4'
import { useMutateAddress } from '@/hooks/useMutateAddress'
import { watch } from 'vue'

const props = defineProps<{
  closeModal: () => void
}>()

const { cep, data: addressCEP, isLoading } = useViaCEP()

const cepForm = useForm({
  defaultValues: { postalCode: '' },
  onSubmit: ({ value }) => {
    console.log('CEP enviado', value)
  }
})


const addressForm = useForm({
  defaultValues: {} as Address,
  onSubmit: async ({ value }) => {
    addAddressMutation.mutate(value)
  },
})

const { addAddressMutation } = useMutateAddress()



// Busca CEP e preenche campos
const handleSearchCEP = async () => {
  const data = addressCEP.value
  if (data) {
    addressForm.setFieldValue('addressLine1', data.logradouro || '')
    addressForm.setFieldValue('neighborhood', data.bairro || '')
    addressForm.setFieldValue('city', data.localidade || '')
    addressForm.setFieldValue('state', data.uf || '')
    addressForm.setFieldValue('country', 'Brasil')
    addressForm.setFieldValue('postalCode', data.cep || '')
  }
}

watch(addressCEP, () => handleSearchCEP())

</script>

<template>
  <form class="mt-4" @submit.prevent.stop="cepForm.handleSubmit">
    <div class="flex flex-row space-y-2 space-x-4">
      <cepForm.Field
        name="postalCode"
        :validators="{
          onChange: z
            .string()
            .min(1, 'Campo necessário.')
            .regex(/^\d{5}-\d{3}$/, 'CEP inválido.'),
        }">
        <template v-slot="{ field }">
          <div class="flex flex-row space-x-2">
            <label class="input">
              <span class="label">CEP</span>
              <input
                id="postalCode"
                type="text"
                placeholder="00000-000"
                :name="field.name"
                :value="field.state.value"
                @input="
                  (e) => {
                    const input = e.target as HTMLInputElement
                    const numbers = input.value.replace(/\D/g, '')
                    const formatted =
                      numbers.length > 5 ? `${numbers.slice(0, 5)}-${numbers.slice(5, 8)}` : numbers
                    field.handleChange(formatted)
                    cep = formatted
                  }
                " />
            </label>
          </div>
        </template>
      </cepForm.Field>
      <button type="submit" class="btn btn-primary" @click="handleSearchCEP" :disabled="isLoading">
        {{ isLoading ? 'Buscando...' : 'Buscar' }}
      </button>
    </div>
    <div class="flex flex-col text-red-500" v-if="!cepForm.getFieldMeta('postalCode')?.isValid">
      <em
        role="alert"
        v-for="(error, index) in cepForm.getFieldMeta('postalCode')?.errors"
        :key="index">
        {{ error?.message }}
      </em>
    </div>
  </form>

  <form class="mt-6" @submit.prevent.stop="addressForm.handleSubmit">
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
      <addressForm.Field
        name="addressLine1"
        :validators="{ onChange: z.string().min(1, 'Campo necessário') }">
        <template v-slot="{ field, state }">
          <div class="form-control w-full">
            <label class="label">
              <span class="label-text">Endereço</span>
            </label>
            <input
              class="input input-bordered"
              type="text"
              placeholder="Rua Dom Pedro II"
              :name="field.name"
              :value="field.state.value"
              @input="(e) => field.handleChange((e.target as HTMLInputElement).value)" />
            <div class="text-error text-sm mt-1" v-if="!field.state.meta.isValid">
              <em v-for="(error, index) in state.meta.errors" :key="index">{{ error?.message }}</em>
            </div>
          </div>
        </template>
      </addressForm.Field>

      <addressForm.Field
        name="addressLine2"
        :validators="{ onChange: z.string().min(1, 'Campo necessário') }">
        <template v-slot="{ field, state }">
          <div class="form-control w-full">
            <label class="label">
              <span class="label-text">Número</span>
            </label>
            <input
              class="input input-bordered"
              type="text"
              placeholder="594"
              :name="field.name"
              :value="field.state.value"
              @input="(e) => field.handleChange((e.target as HTMLInputElement).value)" />
            <div class="text-error text-sm mt-1" v-if="!field.state.meta.isValid">
              <em v-for="(error, index) in state.meta.errors" :key="index">{{ error?.message }}</em>
            </div>
          </div>
        </template>
      </addressForm.Field>

      <addressForm.Field
        name="neighborhood"
        :validators="{ onChange: z.string().min(1, 'Campo necessário') }">
        <template v-slot="{ field, state }">
          <div class="form-control w-full">
            <label class="label">
              <span class="label-text">Bairro</span>
            </label>
            <input
              class="input input-bordered"
              type="text"
              placeholder="Jardim Liberdade"
              :name="field.name"
              :value="field.state.value"
              @input="(e) => field.handleChange((e.target as HTMLInputElement).value)" />
            <div class="text-error text-sm mt-1" v-if="!field.state.meta.isValid">
              <em v-for="(error, index) in state.meta.errors" :key="index">{{ error?.message }}</em>
            </div>
          </div>
        </template>
      </addressForm.Field>

      <addressForm.Field
        name="city"
        :validators="{ onChange: z.string().min(1, 'Campo necessário') }">
        <template v-slot="{ field, state }">
          <div class="form-control w-full">
            <label class="label">
              <span class="label-text">Cidade</span>
            </label>
            <input
              class="input input-bordered"
              type="text"
              placeholder="São Paulo"
              :name="field.name"
              :value="field.state.value"
              @input="(e) => field.handleChange((e.target as HTMLInputElement).value)" />
            <div class="text-error text-sm mt-1" v-if="!field.state.meta.isValid">
              <em v-for="(error, index) in state.meta.errors" :key="index">{{ error?.message }}</em>
            </div>
          </div>
        </template>
      </addressForm.Field>

      <addressForm.Field
        name="state"
        :validators="{ onChange: z.string().min(1, 'Campo necessário') }">
        <template v-slot="{ field, state }">
          <div class="form-control w-full">
            <label class="label">
              <span class="label-text">Estado</span>
            </label>
            <input
              class="input input-bordered"
              type="text"
              placeholder="SP"
              :name="field.name"
              :value="field.state.value"
              @input="(e) => field.handleChange((e.target as HTMLInputElement).value)" />
            <div class="text-error text-sm mt-1" v-if="!field.state.meta.isValid">
              <em v-for="(error, index) in state.meta.errors" :key="index">{{ error?.message }}</em>
            </div>
          </div>
        </template>
      </addressForm.Field>

      <addressForm.Field
        name="country"
        :validators="{ onChange: z.string().min(1, 'Campo necessário') }">
        <template v-slot="{ field, state }">
          <div class="form-control w-full">
            <label class="label">
              <span class="label-text">País</span>
            </label>
            <input
              class="input input-bordered"
              type="text"
              placeholder="Brasil"
              :name="field.name"
              :value="field.state.value"
              @input="(e) => field.handleChange((e.target as HTMLInputElement).value)" />
            <div class="text-error text-sm mt-1" v-if="!field.state.meta.isValid">
              <em v-for="(error, index) in state.meta.errors" :key="index">{{ error?.message }}</em>
            </div>
          </div>
        </template>
      </addressForm.Field>

      <addressForm.Field
        name="name"
        :validators="{ onChange: z.string().min(1, 'Campo necessário') }">
        <template v-slot="{ field, state }">
          <div class="form-control w-full">
            <label class="label">
              <span class="label-text">Nome</span>
            </label>
            <input
              class="input input-bordered"
              type="text"
              placeholder="Casa"
              :name="field.name"
              :value="field.state.value"
              @input="(e) => field.handleChange((e.target as HTMLInputElement).value)" />
            <div class="text-error text-sm mt-1" v-if="!field.state.meta.isValid">
              <em v-for="(error, index) in state.meta.errors" :key="index">{{ error?.message }}</em>
            </div>
          </div>
        </template>
      </addressForm.Field>
    </div>

    <div class="mt-6 flex flex-row space-x-4 items-center justify-center">
      <button type="button" class="btn btn-secondary" @click="props.closeModal">Cancelar</button>
      <button type="submit" class="btn btn-primary" :disabled="isLoading">
        {{ isLoading ? 'Salvando...' : 'Salvar endereço' }}
      </button>
    </div>
  </form>
</template>

// next/src/components/form/form-add-address.tsx
'use client'
import { useMutateAddress } from '@/hooks/flyfood/useMutateAddress'
import { useViaCEP } from '@/hooks/useViaCEP'
import type { Address } from '@/service/flyfood-api/types'
import React, { useEffect } from 'react'
import { useForm } from 'react-hook-form'

type Props = {
  closeModal: () => void
}

export default function FormAddAddress({ closeModal }: Props) {
  const {
    register,
    handleSubmit,
    reset,
    clearErrors,
    watch,
    setValue,
    formState: { errors }
  } = useForm<Address>({
    mode: 'onChange'
  })

  const postalCode = watch('postalCode')
  const { addAddressMutation } = useMutateAddress()
  const { addressCEP, isLoading } = useViaCEP(postalCode)

  const handleGetCEP = async () => {
    if (addressCEP) {
      setValue('addressLine1', addressCEP.logradouro || '')
      setValue('neighborhood', addressCEP.bairro || '')
      setValue('city', addressCEP.localidade || '')
      setValue('state', addressCEP.uf || '')
      setValue('country', 'Brasil')
    }
  }

  const handleAddAddress = async (addr: Address) => {
    clearErrors()
    await addAddressMutation.mutateAsync(addr)
    reset()
    closeModal()
  }

  useEffect(() => {
    if (addAddressMutation.isSuccess) {
      reset()
      closeModal()
    }
  }, [addAddressMutation.isSuccess, closeModal, reset])

  return (
    <form
      onSubmit={handleSubmit(handleAddAddress)}
      className='form-control space-y-8'
    >
      {/* CEP */}
      <div className='flex flex-col'>
        <label htmlFor='postalCode'>CEP</label>
        <div className='flex flex-row space-x-4'>
          <input
            id='postalCode'
            {...register('postalCode', {
              required: 'Este campo é obrigatório',
              pattern: {
                value: /^\d{5}-\d{3}$/,
                message: 'CEP inválido'
              }
            })}
            placeholder='00000-000'
            className='input input-bordered input-primary w-1/2'
          />
          <button
            type='button'
            onClick={handleGetCEP}
            disabled={isLoading}
            className='btn btn-primary'
          >
            {isLoading ? 'Buscando...' : 'Buscar CEP'}
          </button>
        </div>

        {errors.postalCode && (
          <p className='text-primary text-sm mt-1'>
            {errors.postalCode.message}
          </p>
        )}
      </div>

      {/* Name */}
      <div className='flex flex-col'>
        <label htmlFor='addressName'>Nome do Endereço</label>
        <input
          id='address_name'
          {...register('name', {
            required: 'Este campo é obrigatório'
          })}
          placeholder='Minha Casa'
          className='input input-bordered input-primary'
        />
        {errors.name && (
          <p className='text-primary text-sm mt-1'>{errors?.name?.message}</p>
        )}
      </div>

      {/* AddressLine1 */}
      <div className='flex flex-col'>
        <label htmlFor='addressLine1'>Endereço</label>
        <input
          id='address_line_1'
          {...register('addressLine1', {
            required: 'Este campo é obrigatório'
          })}
          placeholder='Rua Dom Pedro I'
          className='input input-bordered input-primary'
        />
        {errors.addressLine1 && (
          <p className='text-primary text-sm mt-1'>
            {errors?.addressLine1?.message}
          </p>
        )}
      </div>

      {/* AddressLine2 */}
      <div className='flex flex-col'>
        <label htmlFor='addressLine2'>Número/Complemento</label>
        <input
          id='address_line_2'
          {...register('addressLine2', {
            required: 'Este campo é obrigatório'
          })}
          placeholder='745 C3'
          className='input input-bordered input-primary'
        />
        {errors.addressLine2 && (
          <p className='text-primary text-sm mt-1'>
            {errors?.addressLine2?.message}
          </p>
        )}
      </div>

      {/* Neighborhood */}
      <div className='flex flex-col'>
        <label htmlFor='neighborhood'>Bairro</label>
        <input
          id='neighborhood'
          {...register('neighborhood', {
            required: 'Este campo é obrigatório'
          })}
          placeholder='Jardim Liberdade'
          className='input input-bordered input-primary'
        />
        {errors.neighborhood && (
          <p className='text-primary text-sm mt-1'>
            {errors?.neighborhood?.message}
          </p>
        )}
      </div>

      {/* City */}
      <div className='flex flex-col'>
        <label htmlFor='city'>Cidade</label>
        <input
          id='city'
          {...register('city', {
            required: 'Este campo é obrigatório'
          })}
          placeholder='São Paulo'
          className='input input-bordered input-primary'
        />
        {errors.city && (
          <p className='text-primary text-sm mt-1'>{errors?.city?.message}</p>
        )}
      </div>

      {/* State */}
      <div className='flex flex-col'>
        <label htmlFor='state'>Estado</label>
        <input
          id='state'
          {...register('state', {
            required: 'Este campo é obrigatório'
          })}
          placeholder='SP'
          className='input input-bordered input-primary'
        />
        {errors.state && (
          <p className='text-primary text-sm mt-1'>{errors?.state?.message}</p>
        )}
      </div>
      <div className='modal-action'>
        <button
          type='button'
          className='btn btn-bg-300'
          onClick={() => {
            reset()
            closeModal()
          }}
        >
          Cancelar
        </button>
        <button
          className='btn btn-primary'
          type='submit'
          disabled={addAddressMutation.isPending}
        >
          {addAddressMutation.isPending ? (
            <span className='loading loading-spinner loading-xs' />
          ) : (
            'Adicionar'
          )}
        </button>
      </div>
    </form>
  )
}
